<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC3lUkcx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC3lUkcx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC3lUkcx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC3lUkcx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerC3lUkcx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'C3lUkcx',
    'container.build_id' => 'e48a1cce',
    'container.build_time' => 1564992517,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC3lUkcx');
